"""create initial postgres schema

Revision ID: 53235f4d0f3c
Revises: 
Create Date: 2026-04-10 03:35:17.656636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53235f4d0f3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.create_table('cell_lines',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Za-z0-9_\\-]+$'", name=op.f('ck_cell_lines_code_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cell_lines')),
    sa.UniqueConstraint('code', name=op.f('uq_cell_lines_code')),
    sa.UniqueConstraint('name', name=op.f('uq_cell_lines_name'))
    )
    op.create_table('file_assets',
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), server_default=sa.text("'fs'"), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('original_image','preprocessed_image','mask','overlay','heatmap','report')", name=op.f('ck_file_assets_asset_type_allowed')),
    sa.CheckConstraint("storage_backend IN ('fs','s3')", name=op.f('ck_file_assets_storage_backend_allowed')),
    sa.CheckConstraint('height IS NULL OR height > 0', name=op.f('ck_file_assets_height_positive_or_null')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_file_assets_size_bytes_non_negative')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_file_assets_width_positive_or_null')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_assets')),
    sa.UniqueConstraint('public_id', name=op.f('uq_file_assets_public_id')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_file_assets_storage_path'))
    )
    op.create_index('ix_file_assets_asset_type_created_at', 'file_assets', ['asset_type', 'created_at'], unique=False)
    op.create_index('ix_file_assets_checksum', 'file_assets', ['checksum'], unique=False)
    op.create_table('models',
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), server_default=sa.text("'pytorch'"), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.CHAR(length=64), nullable=True),
    sa.Column('input_width', sa.Integer(), nullable=False),
    sa.Column('input_height', sa.Integer(), nullable=False),
    sa.Column('input_channels', sa.SmallInteger(), nullable=False),
    sa.Column('preprocessing_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('postprocessing_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence_threshold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("task_type IN ('time_classification','cpe_segmentation','cpe_scoring')", name=op.f('ck_models_task_type_allowed')),
    sa.CheckConstraint('confidence_threshold IS NULL OR (confidence_threshold >= 0 AND confidence_threshold <= 1)', name=op.f('ck_models_confidence_threshold_between_0_1')),
    sa.CheckConstraint('input_channels IN (1,3)', name=op.f('ck_models_input_channels_allowed')),
    sa.CheckConstraint('input_height > 0', name=op.f('ck_models_input_height_positive')),
    sa.CheckConstraint('input_width > 0', name=op.f('ck_models_input_width_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('model_key', name=op.f('uq_models_model_key')),
    sa.UniqueConstraint('task_type', 'name', 'version', name='uq_models_task_type_name_version')
    )
    op.create_index('ix_models_task_type_is_active', 'models', ['task_type', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=30), server_default=sa.text("'researcher'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('researcher','admin')", name=op.f('ck_users_role_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_users_public_id'))
    )
    op.create_table('viruses',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[a-z0-9_]+$'", name=op.f('ck_viruses_code_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viruses')),
    sa.UniqueConstraint('code', name=op.f('uq_viruses_code')),
    sa.UniqueConstraint('name', name=op.f('uq_viruses_name'))
    )
    op.create_table('inference_profiles',
    sa.Column('profile_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('virus_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_line_id', sa.BigInteger(), nullable=False),
    sa.Column('classifier_model_id', sa.BigInteger(), nullable=True),
    sa.Column('segmenter_model_id', sa.BigInteger(), nullable=True),
    sa.Column('scorer_model_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(classifier_model_id IS NOT NULL OR segmenter_model_id IS NOT NULL OR scorer_model_id IS NOT NULL)', name=op.f('ck_inference_profiles_has_any_model')),
    sa.ForeignKeyConstraint(['cell_line_id'], ['cell_lines.id'], name=op.f('fk_inference_profiles_cell_line_id_cell_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['classifier_model_id'], ['models.id'], name=op.f('fk_inference_profiles_classifier_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scorer_model_id'], ['models.id'], name=op.f('fk_inference_profiles_scorer_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segmenter_model_id'], ['models.id'], name=op.f('fk_inference_profiles_segmenter_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['virus_id'], ['viruses.id'], name=op.f('fk_inference_profiles_virus_id_viruses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_profiles')),
    sa.UniqueConstraint('profile_key', name=op.f('uq_inference_profiles_profile_key'))
    )
    op.create_index('ix_inference_profiles_virus_cell_line_is_active', 'inference_profiles', ['virus_id', 'cell_line_id', 'is_active'], unique=False)
    op.create_index('ux_inference_profiles_default_pair', 'inference_profiles', ['virus_id', 'cell_line_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    op.create_table('analysis_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('client_token', sa.UUID(), nullable=True),
    sa.Column('virus_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_line_id', sa.BigInteger(), nullable=False),
    sa.Column('inference_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('images_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_images_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_images_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','queued','processing','completed','failed','cancelled')", name=op.f('ck_analysis_sessions_status_allowed')),
    sa.CheckConstraint('completed_images_count + failed_images_count <= images_count', name=op.f('ck_analysis_sessions_finished_counts_lte_images_count')),
    sa.CheckConstraint('completed_images_count >= 0', name=op.f('ck_analysis_sessions_completed_images_count_non_negative')),
    sa.CheckConstraint('failed_images_count >= 0', name=op.f('ck_analysis_sessions_failed_images_count_non_negative')),
    sa.CheckConstraint('images_count >= 0', name=op.f('ck_analysis_sessions_images_count_non_negative')),
    sa.ForeignKeyConstraint(['cell_line_id'], ['cell_lines.id'], name=op.f('fk_analysis_sessions_cell_line_id_cell_lines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inference_profile_id'], ['inference_profiles.id'], name=op.f('fk_analysis_sessions_inference_profile_id_inference_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analysis_sessions_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['virus_id'], ['viruses.id'], name=op.f('fk_analysis_sessions_virus_id_viruses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_sessions')),
    sa.UniqueConstraint('public_id', name=op.f('uq_analysis_sessions_public_id'))
    )
    op.create_index('ix_analysis_sessions_client_token_created_at', 'analysis_sessions', ['client_token', 'created_at'], unique=False)
    op.create_index('ix_analysis_sessions_status_created_at', 'analysis_sessions', ['status', 'created_at'], unique=False)
    op.create_index('ix_analysis_sessions_user_created_at', 'analysis_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_analysis_sessions_virus_cell_line_created_at', 'analysis_sessions', ['virus_id', 'cell_line_id', 'created_at'], unique=False)
    op.create_table('analysis_images',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('checksum', sa.CHAR(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('preprocessed_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded','queued','processing','completed','failed')", name=op.f('ck_analysis_images_status_allowed')),
    sa.CheckConstraint('channels IS NULL OR channels BETWEEN 1 AND 4', name=op.f('ck_analysis_images_channels_between_1_4_or_null')),
    sa.CheckConstraint('height IS NULL OR height > 0', name=op.f('ck_analysis_images_height_positive_or_null')),
    sa.CheckConstraint('image_index > 0', name=op.f('ck_analysis_images_image_index_positive')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_analysis_images_width_positive_or_null')),
    sa.ForeignKeyConstraint(['original_asset_id'], ['file_assets.id'], name=op.f('fk_analysis_images_original_asset_id_file_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['preprocessed_asset_id'], ['file_assets.id'], name=op.f('fk_analysis_images_preprocessed_asset_id_file_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], name=op.f('fk_analysis_images_session_id_analysis_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_images')),
    sa.UniqueConstraint('public_id', name=op.f('uq_analysis_images_public_id')),
    sa.UniqueConstraint('session_id', 'image_index', name='uq_analysis_images_session_image_index')
    )
    op.create_index('ix_analysis_images_checksum', 'analysis_images', ['checksum'], unique=False)
    op.create_index('ix_analysis_images_session_status', 'analysis_images', ['session_id', 'status'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=30), server_default=sa.text("'analysis'"), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_no', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('analysis')", name=op.f('ck_processing_jobs_job_type_allowed')),
    sa.CheckConstraint("status IN ('queued','processing','completed','failed')", name=op.f('ck_processing_jobs_status_allowed')),
    sa.CheckConstraint('attempt_no > 0', name=op.f('ck_processing_jobs_attempt_no_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], name=op.f('fk_processing_jobs_session_id_analysis_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs')),
    sa.UniqueConstraint('session_id', 'job_type', name='uq_processing_jobs_session_job_type')
    )
    op.create_index('ix_processing_jobs_active_queue', 'processing_jobs', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('queued','processing')"))
    op.create_index('ix_processing_jobs_status_created_at', 'processing_jobs', ['status', 'created_at'], unique=False)
    op.create_table('image_analysis_results',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('classifier_model_id', sa.BigInteger(), nullable=True),
    sa.Column('segmenter_model_id', sa.BigInteger(), nullable=True),
    sa.Column('scorer_model_id', sa.BigInteger(), nullable=True),
    sa.Column('predicted_time_class', sa.String(length=50), nullable=True),
    sa.Column('predicted_time_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('top2_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_flag', sa.String(length=20), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('cpe_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cpe_severity_label', sa.String(length=30), nullable=True),
    sa.Column('cpe_area_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('mask_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('overlay_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('heatmap_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence_flag IN ('normal','low','very_low')", name=op.f('ck_image_analysis_results_confidence_flag_allowed')),
    sa.CheckConstraint('cpe_area_percent IS NULL OR (cpe_area_percent >= 0 AND cpe_area_percent <= 100)', name=op.f('ck_image_analysis_results_cpe_area_percent_between_0_100')),
    sa.CheckConstraint('cpe_score IS NULL OR cpe_score >= 0', name=op.f('ck_image_analysis_results_cpe_score_non_negative_or_null')),
    sa.CheckConstraint('inference_time_ms IS NULL OR inference_time_ms >= 0', name=op.f('ck_image_analysis_results_inference_time_ms_non_negative_or_null')),
    sa.CheckConstraint('predicted_time_confidence IS NULL OR (predicted_time_confidence >= 0 AND predicted_time_confidence <= 1)', name=op.f('ck_image_analysis_results_predicted_time_confidence_between_0_1')),
    sa.ForeignKeyConstraint(['classifier_model_id'], ['models.id'], name=op.f('fk_image_analysis_results_classifier_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['heatmap_asset_id'], ['file_assets.id'], name=op.f('fk_image_analysis_results_heatmap_asset_id_file_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['image_id'], ['analysis_images.id'], name=op.f('fk_image_analysis_results_image_id_analysis_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mask_asset_id'], ['file_assets.id'], name=op.f('fk_image_analysis_results_mask_asset_id_file_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['overlay_asset_id'], ['file_assets.id'], name=op.f('fk_image_analysis_results_overlay_asset_id_file_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scorer_model_id'], ['models.id'], name=op.f('fk_image_analysis_results_scorer_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segmenter_model_id'], ['models.id'], name=op.f('fk_image_analysis_results_segmenter_model_id_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_analysis_results')),
    sa.UniqueConstraint('image_id', name=op.f('uq_image_analysis_results_image_id'))
    )
    op.create_index('ix_image_analysis_results_cpe_severity_label', 'image_analysis_results', ['cpe_severity_label'], unique=False)
    op.create_index('ix_image_analysis_results_predicted_time_class', 'image_analysis_results', ['predicted_time_class'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_analysis_results_predicted_time_class', table_name='image_analysis_results')
    op.drop_index('ix_image_analysis_results_cpe_severity_label', table_name='image_analysis_results')
    op.drop_table('image_analysis_results')
    op.drop_index('ix_processing_jobs_status_created_at', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_active_queue', table_name='processing_jobs', postgresql_where=sa.text("status IN ('queued','processing')"))
    op.drop_table('processing_jobs')
    op.drop_index('ix_analysis_images_session_status', table_name='analysis_images')
    op.drop_index('ix_analysis_images_checksum', table_name='analysis_images')
    op.drop_table('analysis_images')
    op.drop_index('ix_analysis_sessions_virus_cell_line_created_at', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_user_created_at', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_status_created_at', table_name='analysis_sessions')
    op.drop_index('ix_analysis_sessions_client_token_created_at', table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    op.drop_index('ux_inference_profiles_default_pair', table_name='inference_profiles', postgresql_where=sa.text('is_default = true'))
    op.drop_index('ix_inference_profiles_virus_cell_line_is_active', table_name='inference_profiles')
    op.drop_table('inference_profiles')
    op.drop_table('viruses')
    op.drop_table('users')
    op.drop_index('ix_models_task_type_is_active', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_file_assets_checksum', table_name='file_assets')
    op.drop_index('ix_file_assets_asset_type_created_at', table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_table('cell_lines')
    # ### end Alembic commands ###
